// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo42yxCXxamWcwPE3zKmp0pO-k2_QKsXw',
    appId: '1:652451640989:web:e85153a4663ce35af0c674',
    messagingSenderId: '652451640989',
    projectId: 'scu-alumni-connect',
    authDomain: 'scu-alumni-connect.firebaseapp.com',
    storageBucket: 'scu-alumni-connect.appspot.com',
    measurementId: 'G-ZTLYKH95JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWBq0qV-f7b4nkTqGEBthqgPnDeoEQVv4',
    appId: '1:652451640989:android:fafeac9a68fae59ef0c674',
    messagingSenderId: '652451640989',
    projectId: 'scu-alumni-connect',
    storageBucket: 'scu-alumni-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawtutcACWOX-xUBM0vP0OMC-OgvVp62o',
    appId: '1:652451640989:ios:c34360ccac2bbecff0c674',
    messagingSenderId: '652451640989',
    projectId: 'scu-alumni-connect',
    storageBucket: 'scu-alumni-connect.appspot.com',
    androidClientId: '652451640989-lhbosvhudujucc1aq63nca36g87e6cvm.apps.googleusercontent.com',
    iosClientId: '652451640989-msluf3tcu783qbvdchfq4ppkbk01lpuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.scuAlumniConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBawtutcACWOX-xUBM0vP0OMC-OgvVp62o',
    appId: '1:652451640989:ios:2ee86d21db50bd17f0c674',
    messagingSenderId: '652451640989',
    projectId: 'scu-alumni-connect',
    storageBucket: 'scu-alumni-connect.appspot.com',
    androidClientId: '652451640989-lhbosvhudujucc1aq63nca36g87e6cvm.apps.googleusercontent.com',
    iosClientId: '652451640989-jcqanlcmb7nl7gk0u514qqe81916c029.apps.googleusercontent.com',
    iosBundleId: 'com.example.scuAlumniConnect.RunnerTests',
  );
}
